Fix input test add popup test
tough-dev-school/lms-frontend pull request #70
Opened 2021-11-09 12:29 UTC by jinonensk

Переписал тесты для инпута, чтобы не общаться ко внутреннему компьютед свойству  так как по идее я ничего не знаю про него

сделал тесты для попапа на открытие закрытие

Вопрос, Федя, может быть ыт знаешь или у тебя примеры есть, вот попам возвращает промис сейчас. и после закрытия резолвится и отдает тру или фолс.

Я как то не придумал как это момент можно протестировать.

2021-11-10 12:34 UTC, f213 requested changes

2021-11-10 12:34 UTC, f213 commented on tests/unit/components/ui-kit/UiInput.spec.js
> +    expect(label.exists()).toBe(true);
Это не очень хороший асёрт:
* Он использует deprected метод — find
* Когда `expect(label.exists()).toBe(true)` упадёт, из сообщения об ошибке будет совершенно непонятно, что случилось — просто что False должно быть True

Если ты хочешь проверить наличие чего-нибудь в HTML — так и проверяй: `expect(wrapper.html()).toMatch('Шотам')`

2021-11-10 12:34 UTC, f213 commented on tests/unit/components/ui-kit/UiInput.spec.js
> +  const PART_OF_DEFAULT_ID = "input-";
Зачем это за рамками теста?

2021-11-10 12:34 UTC, f213 commented on tests/unit/components/ui-kit/UiInput.spec.js
> +    expect(label.exists()).toBe(true);
Тут тоже плохой асёрт.

2021-11-10 12:34 UTC, f213 commented on tests/unit/components/ui-kit/UiPopup.spec.js
> +    expect(overlay).toBe(undefined);
Есть же специальный [асёрт](https://jestjs.io/docs/expect#tobeundefined).

2021-11-10 12:34 UTC, f213 commented on tests/unit/components/ui-kit/UiPopup.spec.js
> +    wrapper.destroy();
Зачем?

2021-11-10 15:22 UTC, jinonensk commented on tests/unit/components/ui-kit/UiInput.spec.js
> +  const PART_OF_DEFAULT_ID = "input-";
Поправил

2021-11-10 15:22 UTC, jinonensk commented on tests/unit/components/ui-kit/UiPopup.spec.js
> +    expect(overlay).toBe(undefined);
о, спасибо. поправил

2021-11-10 15:30 UTC, jinonensk commented on tests/unit/components/ui-kit/UiPopup.spec.js
> +    wrapper.destroy();
Потому что я создаю теперь локальный враппер для каждого деста, и вынес его на уровень выше. Так можно писть всякие вспомоигательные функции, которые будут обращаться к нему через замыкание.

Но для чистоты надо дестроить враппер после теста. Это спасет от ситаций, если например, не вызывал функцию createComponent и начал работать на старом компоненте.

А так гарантирует, что будет новый тест - новые данные. И не ошибешься.

2021-11-10 15:30 UTC, jinonensk commented on tests/unit/components/ui-kit/UiInput.spec.js
> +    expect(label.exists()).toBe(true);
Поправил

2021-11-10 15:42 UTC, jinonensk commented on tests/unit/components/ui-kit/UiInput.spec.js
> +    expect(label.exists()).toBe(true);
Тут есть вопросы.

Поправил это вот в тестах с лейблом и инпутом.
Понял ,что ты имел ввиду про отображение ошибок. Окей.

но

на счет find - не совсем так, он депрекейтед только для поиска компонентов. И вместо него теперь findComponent, но никакого другого способа тайти обычный html-тэг нет. Тут я просто обычный лейбл по валидном css-селектору ищу.

У меня например есть тест, на откртиые попапа. и я там ищу наличие оверлея. просто div
Тут мне кажется уже большой разницы не будет. 
```js
expect('').toMatch(<div)
или
expect(undefined).toBe(true)
```
К слову это тоже я не сам выдумал :) в гитлабе так делаю, взял как бестпрактис прост.
```js
expect(label.exists()).toBe(true);
```

**Итого** правильно ли я понимаю, что ты во всех тестах на наличие элемена предлагаешь через поиск строки в html делать?

2021-11-11 17:39 UTC, f213 commented on tests/unit/components/ui-kit/UiInput.spec.js
> +    expect(label.exists()).toBe(true);
> Итого правильно ли я понимаю, что ты во всех тестах на наличие элемена предлагаешь через поиск строки в html делать?

Да, я не увидел ни одного аргумента, который бы меня убедил так не делать.

2021-11-11 17:40 UTC, f213 reviewed
Не смогу больше смотреть этот код. Если ты доволен — давай мёрджить.

2021-11-12 18:41 UTC, merged